version: "3.9"

services:
  web:
    image: kumardatta07/my-web-app:latest  # Fixed the image reference format
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
